/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaInterfaz;

import capaLogica.Cajero;
import capaLogica.Cuenta;
import java.awt.HeadlessException;
import javax.swing.JOptionPane;
//import capaLogica.memoriaCajero;

/**
 *
 * @author Sebas
 */
public class FrmAdministrador extends javax.swing.JFrame {

    Cuenta cuenta1;

    /**
     * Creates new form FrmAdministrador
     */
    public FrmAdministrador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel3 = new javax.swing.JLabel();
        jBtnSiguiente = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jRdbCrearCuenta = new javax.swing.JRadioButton();
        jRdbReporteDeCuentasPin = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(705, 280));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("Seleccione una opción:");

        jBtnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnSiguiente.setText("Siguiente");
        jBtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSiguienteActionPerformed(evt);
            }
        });

        jBtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        buttonGroup1.add(jRdbCrearCuenta);
        jRdbCrearCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbCrearCuenta.setText("1. Crear cuenta");

        buttonGroup1.add(jRdbReporteDeCuentasPin);
        jRdbReporteDeCuentasPin.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbReporteDeCuentasPin.setText("2. Reporte de cuentas con su pin");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(574, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(jBtnSiguiente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(29, 29, 29))
            .addGroup(layout.createSequentialGroup()
                .addGap(69, 69, 69)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jRdbReporteDeCuentasPin)
                    .addComponent(jRdbCrearCuenta)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jRdbCrearCuenta)
                .addGap(18, 18, 18)
                .addComponent(jRdbReporteDeCuentasPin)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jBtnSiguiente, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSiguienteActionPerformed
        String nomCompleto = "";
        String cedula = "";
        String password = "";
        String passwordCod = "";
        String numTelf = "";
        double saldoInicial = 0.0;

        if (jRdbCrearCuenta.isSelected()) { //Para la creacion de la cuenta en el modo admin

            Cuenta cuenta1 = new Cuenta();
            String sNomCompleto = JOptionPane.showInputDialog(this, "Digite su nombre completo.\nEjemplo: Cascante Bolaños Sebastián");
            String sCedula = JOptionPane.showInputDialog(this, "Digite su número de cédula.");
            String sNumTelf = JOptionPane.showInputDialog(this, "Digite su número de teléfono.");
            String sSaldoInicial = JOptionPane.showInputDialog(this, "Digite el saldo.");
            if (sNomCompleto == null && sCedula == null && sNumTelf == null && sSaldoInicial == null) {

            } else {
                nomCompleto = sNomCompleto;
                cedula = sCedula;
                numTelf = sNumTelf;
                try {
                    saldoInicial = Double.parseDouble(sSaldoInicial);
                } catch (NumberFormatException numberFormatException) {
                    JOptionPane.showMessageDialog(this, "Digite únicamente valores numéricos", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }

                cuenta1.setNumTelf(numTelf);
                cuenta1.setNomCompleto(nomCompleto);
                cuenta1.setCedula(cedula);
                cuenta1.setSaldoActual(saldoInicial);
                password = cuenta1.crearContra();
                cuenta1.setPassword(password);
                passwordCod = cuenta1.codificarClave();
                cuenta1.setPasswordCod(passwordCod);

                JOptionPane.showMessageDialog(this, PrincipalSoftwareBancario.getCajero1().crearCuenta(cuenta1));
                cuenta1.setNumCuenta();
            }

        }
        if (jRdbReporteDeCuentasPin.isSelected()) { //Para solicitar una cuenta en el modo admin

            String pin = ""; 
                   
            String sPin = JOptionPane.showInputDialog("Digite el Pin de la cuenta que desea buscar");
            if(sPin==null){
                
            }else{
            pin=sPin;
            JOptionPane.showMessageDialog(this, PrincipalSoftwareBancario.getCajero1().buscarCuenta(pin));//toma el metodo buscarCuenta... de la clase cajero por medio de la clase memoriaCajer
            }
        }


    }//GEN-LAST:event_jBtnSiguienteActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.dispose();
        FrmMenuPrincipal frmMenuPrincipal = new FrmMenuPrincipal();
        frmMenuPrincipal.setVisible(true);
        frmMenuPrincipal.setLocationRelativeTo(null);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmAdministrador.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmAdministrador().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jBtnSiguiente;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JRadioButton jRdbCrearCuenta;
    private javax.swing.JRadioButton jRdbReporteDeCuentasPin;
    // End of variables declaration//GEN-END:variables
}
