/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaInterfaz;

import javax.swing.JOptionPane;
import capaLogica.Cuenta;
import capaLogica.Cajero;
//import capaLogica.memoriaCajero;

/**
 *
 * @author Sebas
 */
public class FrmMenuPrincipal extends javax.swing.JFrame {

    Cuenta cuenta1;
    Cajero cajero1;
    public static int contIntentos = 0;

    /**
     * Creates new form FrmMenuPrincipal
     */
    public FrmMenuPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblNumeroCuenta = new javax.swing.JLabel();
        jLblPIN = new javax.swing.JLabel();
        jTxtNumCuenta = new javax.swing.JTextField();
        jTxtPIN = new javax.swing.JTextField();
        jBtnIniciarSesion = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        jLblNumeroCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblNumeroCuenta.setText("Número de Cuenta");

        jLblPIN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLblPIN.setText("PIN");

        jTxtNumCuenta.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTxtNumCuenta.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtNumCuenta.setText("Ejemplo: 12345");
        jTxtNumCuenta.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtNumCuentaMouseClicked(evt);
            }
        });
        jTxtNumCuenta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtNumCuentaActionPerformed(evt);
            }
        });

        jTxtPIN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jTxtPIN.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTxtPIN.setText("Ejemplo: 1234");
        jTxtPIN.setPreferredSize(new java.awt.Dimension(120, 26));
        jTxtPIN.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTxtPINMouseClicked(evt);
            }
        });
        jTxtPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtPINActionPerformed(evt);
            }
        });

        jBtnIniciarSesion.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnIniciarSesion.setText("Iniciar Sesión");
        jBtnIniciarSesion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIniciarSesionActionPerformed(evt);
            }
        });

        jBtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblNumeroCuenta)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLblPIN)
                        .addGap(56, 56, 56)))
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTxtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 315, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(151, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBtnIniciarSesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblNumeroCuenta)
                    .addComponent(jTxtNumCuenta, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblPIN)
                    .addComponent(jTxtPIN, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jBtnIniciarSesion, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jBtnSalir, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened

    }//GEN-LAST:event_formWindowOpened

    private void jTxtNumCuentaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtNumCuentaActionPerformed
        jTxtPIN.requestFocus();
        jTxtPIN.setText("");
    }//GEN-LAST:event_jTxtNumCuentaActionPerformed

    private void jBtnIniciarSesionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIniciarSesionActionPerformed
        final String UsuarioAdmin = "99999";
        final String PinAdmin = "12345";

        int usuario = 0;
        String pin = null;

        try {
            usuario = Integer.parseInt(jTxtNumCuenta.getText());
            pin = jTxtPIN.getText();
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "ERROR\nLa cuenta no existe\nSu número de cuenta o su PIN son incorrectos");
            return;
        }

        if (jTxtNumCuenta.getText().equals(UsuarioAdmin) && jTxtPIN.getText().equals(PinAdmin)) { //Para admin
            this.dispose();
            FrmAdministrador frmAdministrador = new FrmAdministrador();
            frmAdministrador.setVisible(true);
            frmAdministrador.setLocationRelativeTo(this);
        } else {
            if (PrincipalSoftwareBancario.getCajero1().iniciarSesion(usuario, pin) == true) { //Para usuario
                this.dispose();
                FrmUsuario frmUsuario = new FrmUsuario();
                frmUsuario.setVisible(true);
                frmUsuario.setLocationRelativeTo(this);
                PrincipalSoftwareBancario.setNumUser(usuario);
                PrincipalSoftwareBancario.setPinUser(pin);
            } else {
                
                JOptionPane.showMessageDialog(this, "ERROR\nLa cuenta no existe\nSu número de cuenta o su PIN son incorrectos");
                contIntentos++;
            }
        }
        if(contIntentos==3){
            JOptionPane.showMessageDialog(this, "Ha fallado 3 veces, el programa se cerrará en 3.2.1...");
            System.exit(0);
        }
    }//GEN-LAST:event_jBtnIniciarSesionActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        System.exit(0);

    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jTxtPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtPINActionPerformed
        jBtnIniciarSesion.doClick();
    }//GEN-LAST:event_jTxtPINActionPerformed

    private void jTxtNumCuentaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtNumCuentaMouseClicked
        jTxtNumCuenta.setText("");
    }//GEN-LAST:event_jTxtNumCuentaMouseClicked

    private void jTxtPINMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTxtPINMouseClicked
        jTxtPIN.setText("");
    }//GEN-LAST:event_jTxtPINMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmMenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmMenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnIniciarSesion;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JLabel jLblNumeroCuenta;
    private javax.swing.JLabel jLblPIN;
    private javax.swing.JTextField jTxtNumCuenta;
    private javax.swing.JTextField jTxtPIN;
    // End of variables declaration//GEN-END:variables
}
