/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package capaInterfaz;

import capaLogica.Cuenta;
import capaLogica.Transaccion;
import java.awt.HeadlessException;
//import capaLogica.memoriaCajero;
import javax.swing.JOptionPane;
//import javax.swing.JPopupMenu;

/**
 *
 * @author Sebas
 */
public class FrmUsuario extends javax.swing.JFrame {

    Cuenta cuenta1;
    Transaccion transaccion1;
    double valor = 0;
    double retiros = 0;

    /**
     * Creates new form FrmUsuario
     */
    public FrmUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jLabel6 = new javax.swing.JLabel();
        jBtnSiguiente = new javax.swing.JButton();
        jBtnSalir = new javax.swing.JButton();
        jRdbConsultaSaldo = new javax.swing.JRadioButton();
        jRdbDeposito = new javax.swing.JRadioButton();
        jRdbRetiro = new javax.swing.JRadioButton();
        jRdbTransferencia = new javax.swing.JRadioButton();
        jRdbPagoServiciosPublicos = new javax.swing.JRadioButton();
        jRdbPagoSinpe = new javax.swing.JRadioButton();
        jRdbReporteMovimientos = new javax.swing.JRadioButton();
        jRdbCambioPIN = new javax.swing.JRadioButton();
        jBtnV1000 = new javax.swing.JButton();
        jBtnV5000 = new javax.swing.JButton();
        jBtnV10000 = new javax.swing.JButton();
        jBtnV20000 = new javax.swing.JButton();
        jBtnV50000 = new javax.swing.JButton();
        jBtnV100000 = new javax.swing.JButton();
        jBtnVOtro = new javax.swing.JButton();
        jTxtOtroMonto = new javax.swing.JTextField();
        jLblPressEnter = new javax.swing.JLabel();
        jRdbPagoElectricidad = new javax.swing.JRadioButton();
        jRdbPagoTelefono = new javax.swing.JRadioButton();
        jRdbPagoServiciosMunicipales = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTxaVoucher = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(954, 430));
        setMinimumSize(new java.awt.Dimension(954, 430));
        setPreferredSize(new java.awt.Dimension(954, 430));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Seleccione una opción:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 21, -1, -1));

        jBtnSiguiente.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnSiguiente.setText("Siguiente");
        jBtnSiguiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSiguienteActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSiguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 290, 110, 32));

        jBtnSalir.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jBtnSalir.setText("Salir");
        jBtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 330, 110, 32));

        buttonGroup1.add(jRdbConsultaSaldo);
        jRdbConsultaSaldo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbConsultaSaldo.setText("1. Consulta de saldo");
        jRdbConsultaSaldo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbConsultaSaldoActionPerformed(evt);
            }
        });
        getContentPane().add(jRdbConsultaSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 59, -1, -1));

        buttonGroup1.add(jRdbDeposito);
        jRdbDeposito.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbDeposito.setText("2. Depósito");
        jRdbDeposito.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbDepositoActionPerformed(evt);
            }
        });
        getContentPane().add(jRdbDeposito, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 89, -1, -1));

        buttonGroup1.add(jRdbRetiro);
        jRdbRetiro.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbRetiro.setText("3. Retiro");
        jRdbRetiro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbRetiroActionPerformed(evt);
            }
        });
        getContentPane().add(jRdbRetiro, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 119, -1, -1));

        buttonGroup1.add(jRdbTransferencia);
        jRdbTransferencia.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbTransferencia.setText("4. Transferencia");
        jRdbTransferencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbTransferenciaActionPerformed(evt);
            }
        });
        getContentPane().add(jRdbTransferencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 149, -1, -1));

        buttonGroup1.add(jRdbPagoServiciosPublicos);
        jRdbPagoServiciosPublicos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbPagoServiciosPublicos.setText("5. Pago de Servicios Públicos");
        jRdbPagoServiciosPublicos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbPagoServiciosPublicosActionPerformed(evt);
            }
        });
        getContentPane().add(jRdbPagoServiciosPublicos, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 179, -1, -1));

        buttonGroup1.add(jRdbPagoSinpe);
        jRdbPagoSinpe.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbPagoSinpe.setText("6. Pago de SINPE");
        jRdbPagoSinpe.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbPagoSinpeActionPerformed(evt);
            }
        });
        getContentPane().add(jRdbPagoSinpe, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 209, -1, -1));

        buttonGroup1.add(jRdbReporteMovimientos);
        jRdbReporteMovimientos.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbReporteMovimientos.setText("7. Reporte de movimientos");
        jRdbReporteMovimientos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbReporteMovimientosActionPerformed(evt);
            }
        });
        getContentPane().add(jRdbReporteMovimientos, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 239, -1, -1));

        buttonGroup1.add(jRdbCambioPIN);
        jRdbCambioPIN.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbCambioPIN.setText("8. Cambio de PIN");
        jRdbCambioPIN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRdbCambioPINActionPerformed(evt);
            }
        });
        getContentPane().add(jRdbCambioPIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(48, 269, -1, -1));

        jBtnV1000.setText("₡1000");
        jBtnV1000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnV1000ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnV1000, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 30, -1, -1));

        jBtnV5000.setText("₡5000");
        jBtnV5000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnV5000ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnV5000, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 60, -1, -1));

        jBtnV10000.setText("₡10000");
        jBtnV10000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnV10000ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnV10000, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 90, -1, -1));

        jBtnV20000.setText("₡20000");
        jBtnV20000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnV20000ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnV20000, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 120, -1, -1));

        jBtnV50000.setText("₡50000");
        jBtnV50000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnV50000ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnV50000, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 150, -1, -1));

        jBtnV100000.setText("₡100000");
        jBtnV100000.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnV100000ActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnV100000, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 180, -1, -1));

        jBtnVOtro.setText("Otro:");
        jBtnVOtro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVOtroActionPerformed(evt);
            }
        });
        getContentPane().add(jBtnVOtro, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 210, -1, -1));

        jTxtOtroMonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtOtroMontoActionPerformed(evt);
            }
        });
        getContentPane().add(jTxtOtroMonto, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 210, 170, -1));

        jLblPressEnter.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLblPressEnter.setText("Presione ENTER para confirmar");
        getContentPane().add(jLblPressEnter, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 230, 190, -1));

        buttonGroup2.add(jRdbPagoElectricidad);
        jRdbPagoElectricidad.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbPagoElectricidad.setText("Pago de electricidad");
        getContentPane().add(jRdbPagoElectricidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 40, -1, -1));

        buttonGroup2.add(jRdbPagoTelefono);
        jRdbPagoTelefono.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbPagoTelefono.setText("Pago de teléfono");
        getContentPane().add(jRdbPagoTelefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 70, -1, -1));

        buttonGroup2.add(jRdbPagoServiciosMunicipales);
        jRdbPagoServiciosMunicipales.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jRdbPagoServiciosMunicipales.setText("Pago de servicios Municipales");
        getContentPane().add(jRdbPagoServiciosMunicipales, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 100, -1, -1));

        jTxaVoucher.setColumns(20);
        jTxaVoucher.setRows(5);
        jTxaVoucher.setEnabled(false);
        jTxaVoucher.setFocusable(false);
        jTxaVoucher.setOpaque(false);
        jScrollPane1.setViewportView(jTxaVoucher);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 20, 320, 360));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnSiguienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSiguienteActionPerformed
        if (jRdbConsultaSaldo.isSelected()) { //para consultar el saldo

            if (PrincipalSoftwareBancario.getCajero1().consultaSaldo() > -1) {
                JOptionPane.showMessageDialog(this, "El saldo actual de su cuenta es de: ₡" + PrincipalSoftwareBancario.getCajero1().consultaSaldo()
                        + "\n\n" + PrincipalSoftwareBancario.getCajero1().datosCuenta());
            } else {
                JOptionPane.showMessageDialog(this, "ERROR\nLa clave o su número de cuenta son incorrectos y no se podrá mostrar su saldo");
            }
        }
        if (jRdbDeposito.isSelected()) {

            double deposito = 0;
            String sDeposito = JOptionPane.showInputDialog(this, "Ingrese la cantidad a depositar");
            if (sDeposito == null) {

            } else {
                try {
                    deposito = Double.parseDouble(sDeposito);

                } catch (NumberFormatException numberFormatException) {
                    JOptionPane.showMessageDialog(this, "Digite únicamente valores numéricos", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                JOptionPane.showMessageDialog(this, PrincipalSoftwareBancario.getCajero1().deposito(deposito));
            }
        }
        if (jRdbRetiro.isSelected()) {
            retiros += valor;
            if (retiros <= 300000) {
                JOptionPane.showMessageDialog(this, PrincipalSoftwareBancario.getCajero1().retiro(valor));
            } else {
                JOptionPane.showMessageDialog(this, "Se exedió la cantidad máxima de retiro diaria\nNO se realizará su retiro", "Lo sentimos", JOptionPane.ERROR_MESSAGE);
            }
        }
        if (jRdbTransferencia.isSelected()) {
            int numCuenta = 0;
            double montoATransferir = 0;
            String sNumCuenta = JOptionPane.showInputDialog(this, "Ingrese la cuenta a la que le desea transferir");
            String sMontoATransferir = JOptionPane.showInputDialog(this, "Ingrese la cantidad a trasnferir");
            if (sNumCuenta == null && sMontoATransferir == null) {

            } else {
                try {
                    numCuenta = Integer.parseInt(sNumCuenta);
                    montoATransferir = Double.parseDouble(sMontoATransferir);
                } catch (NumberFormatException numberFormatException) {
                    JOptionPane.showMessageDialog(this, "Digite únicamente valores numéricos", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                JOptionPane.showMessageDialog(this, PrincipalSoftwareBancario.getCajero1().trasnferencia(numCuenta, montoATransferir));
            }
        }
        if (jRdbPagoServiciosPublicos.isSelected()) {
            if (jRdbPagoElectricidad.isSelected()) {
                String NISE = "";
                double montoPago = 0;
                String sNISE = JOptionPane.showInputDialog(this, "Ingrese su NISE");
                String sMontoPago = JOptionPane.showInputDialog(this, "Ingrese el monto a pagar");
                
                if(sNISE==null&&sMontoPago==null){
                }else{
                    NISE = sNISE;
                try {
                    montoPago = Double.parseDouble(sMontoPago);
                } catch (NumberFormatException numberFormatException) {
                    JOptionPane.showMessageDialog(this, "Digite únicamente valores numéricos", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                JOptionPane.showMessageDialog(this, PrincipalSoftwareBancario.getCajero1().pagoDeElectricidad(NISE, montoPago));
                }
            }
            if (jRdbPagoTelefono.isSelected()) {
                String numTelf = "";
                double montoPago = 0;
                String sNumTelf = JOptionPane.showInputDialog(this, "Ingrese su número de teléfono");
                String sMontoPago =JOptionPane.showInputDialog(this, "Ingrese el monto a pagar");
                if(sNumTelf==null&&sMontoPago==null){
                    
                }else{
                    numTelf = sNumTelf;
                try {
                    montoPago = Double.parseDouble(sMontoPago);
                } catch (NumberFormatException numberFormatException) {
                    JOptionPane.showMessageDialog(this, "Digite únicamente valores numéricos", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                JOptionPane.showMessageDialog(this, PrincipalSoftwareBancario.getCajero1().pagoDeTelefono(numTelf, montoPago));
                }
            }
            if (jRdbPagoServiciosMunicipales.isSelected()) {
                double montoPago = 0;
                String sMontoPago = JOptionPane.showInputDialog(this, "Ingrese el monto a pagar");
                if(sMontoPago==null){
                    
                }else{
                try {
                    montoPago = Double.parseDouble(sMontoPago);
                } catch (NumberFormatException numberFormatException) {
                    JOptionPane.showMessageDialog(this, "Digite únicamente valores numéricos", "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                JOptionPane.showMessageDialog(this, PrincipalSoftwareBancario.getCajero1().pagoDeServiciosMunicipales(montoPago));
                }
            }
        }
        if (jRdbPagoSinpe.isSelected()) {
            String numTelf = "";
            double montoPago = 0;
            String sNumTelf = JOptionPane.showInputDialog(this, "Ingrese su número de teléfono");
            String sMontoPago = JOptionPane.showInputDialog(this, "Ingrese el monto del SINPE");
            if(sNumTelf==null&&sMontoPago==null){
                
            }else{
                numTelf = sNumTelf;
            try {
                montoPago = Double.parseDouble(sMontoPago);
            } catch (NumberFormatException numberFormatException) {
                JOptionPane.showMessageDialog(this, "Digite únicamente valores numéricos", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            JOptionPane.showMessageDialog(this, PrincipalSoftwareBancario.getCajero1().pagoSINPE(numTelf, montoPago));
            }
        }
        if (jRdbReporteMovimientos.isSelected()) {
            jTxaVoucher.setText(PrincipalSoftwareBancario.getCajero1().reporteMovimientos());
        }
        if (jRdbCambioPIN.isSelected()) {
            String nuevoPin = "";
            String pinAnterior = "";
            
            
            String sPinAnterior = JOptionPane.showInputDialog(this, "Ingrese su PIN actual");
            String sNuevoPin = JOptionPane.showInputDialog(this, "Ingrese el nuevo PIN\nDebe ser de 4 caracteris númericos");
            if(sPinAnterior==null&&sNuevoPin==null){
                
            }else{
                nuevoPin = sNuevoPin;
                pinAnterior = sPinAnterior;
            JOptionPane.showMessageDialog(this, PrincipalSoftwareBancario.getCajero1().cambioPin(nuevoPin, pinAnterior));
            }
        }
    }//GEN-LAST:event_jBtnSiguienteActionPerformed

    private void jBtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnSalirActionPerformed
        this.dispose();
        FrmMenuPrincipal frmMenuPrincipal = new FrmMenuPrincipal();
        frmMenuPrincipal.setVisible(true);
        frmMenuPrincipal.setLocationRelativeTo(null);
    }//GEN-LAST:event_jBtnSalirActionPerformed

    private void jBtnV50000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnV50000ActionPerformed
        valor = 50000;
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnSiguiente.doClick();
    }//GEN-LAST:event_jBtnV50000ActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnV1000.setVisible(false);
        jBtnV5000.setVisible(false);
        jBtnV10000.setVisible(false);
        jBtnV20000.setVisible(false);
        jBtnV50000.setVisible(false);
        jBtnV100000.setVisible(false);
        jBtnVOtro.setVisible(false);
        jRdbPagoElectricidad.setVisible(false);
        jRdbPagoTelefono.setVisible(false);
        jRdbPagoServiciosMunicipales.setVisible(false);
        jRdbPagoElectricidad.setEnabled(false);
        jRdbPagoTelefono.setEnabled(false);
        jRdbPagoServiciosMunicipales.setEnabled(false);
    }//GEN-LAST:event_formWindowOpened

    private void jRdbRetiroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbRetiroActionPerformed
        jBtnV1000.setVisible(true);
        jBtnV5000.setVisible(true);
        jBtnV10000.setVisible(true);
        jBtnV20000.setVisible(true);
        jBtnV50000.setVisible(true);
        jBtnV100000.setVisible(true);
        jBtnVOtro.setVisible(true);
        jRdbPagoElectricidad.setVisible(false);
        jRdbPagoTelefono.setVisible(false);
        jRdbPagoServiciosMunicipales.setVisible(false);
        jRdbPagoElectricidad.setEnabled(false);
        jRdbPagoTelefono.setEnabled(false);
        jRdbPagoServiciosMunicipales.setEnabled(false);
    }//GEN-LAST:event_jRdbRetiroActionPerformed

    private void jBtnVOtroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVOtroActionPerformed
        jTxtOtroMonto.setVisible(true);
        jLblPressEnter.setVisible(true);
    }//GEN-LAST:event_jBtnVOtroActionPerformed

    private void jBtnV1000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnV1000ActionPerformed
        valor = 1000;
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnSiguiente.doClick();

    }//GEN-LAST:event_jBtnV1000ActionPerformed

    private void jBtnV5000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnV5000ActionPerformed
        valor = 5000;
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnSiguiente.doClick();
    }//GEN-LAST:event_jBtnV5000ActionPerformed

    private void jBtnV10000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnV10000ActionPerformed
        valor = 10000;
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnSiguiente.doClick();
    }//GEN-LAST:event_jBtnV10000ActionPerformed

    private void jBtnV20000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnV20000ActionPerformed
        valor = 20000;
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnSiguiente.doClick();
    }//GEN-LAST:event_jBtnV20000ActionPerformed

    private void jBtnV100000ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnV100000ActionPerformed
        valor = 100000;
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnSiguiente.doClick();
    }//GEN-LAST:event_jBtnV100000ActionPerformed

    private void jTxtOtroMontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtOtroMontoActionPerformed
        try {
            valor = Double.parseDouble(jTxtOtroMonto.getText());
        } catch (NumberFormatException numberFormatException) {
            JOptionPane.showMessageDialog(this, "Digite únicamente valores numéricos", "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        jBtnSiguiente.doClick();
    }//GEN-LAST:event_jTxtOtroMontoActionPerformed

    private void jRdbConsultaSaldoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbConsultaSaldoActionPerformed
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnV1000.setVisible(false);
        jBtnV5000.setVisible(false);
        jBtnV10000.setVisible(false);
        jBtnV20000.setVisible(false);
        jBtnV50000.setVisible(false);
        jBtnV100000.setVisible(false);
        jBtnVOtro.setVisible(false);
        jRdbPagoElectricidad.setVisible(false);
        jRdbPagoTelefono.setVisible(false);
        jRdbPagoServiciosMunicipales.setVisible(false);
        jRdbPagoElectricidad.setEnabled(false);
        jRdbPagoTelefono.setEnabled(false);
        jRdbPagoServiciosMunicipales.setEnabled(false);
    }//GEN-LAST:event_jRdbConsultaSaldoActionPerformed

    private void jRdbDepositoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbDepositoActionPerformed
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnV1000.setVisible(false);
        jBtnV5000.setVisible(false);
        jBtnV10000.setVisible(false);
        jBtnV20000.setVisible(false);
        jBtnV50000.setVisible(false);
        jBtnV100000.setVisible(false);
        jBtnVOtro.setVisible(false);
        jRdbPagoElectricidad.setVisible(false);
        jRdbPagoTelefono.setVisible(false);
        jRdbPagoServiciosMunicipales.setVisible(false);
        jRdbPagoElectricidad.setEnabled(false);
        jRdbPagoTelefono.setEnabled(false);
        jRdbPagoServiciosMunicipales.setEnabled(false);
    }//GEN-LAST:event_jRdbDepositoActionPerformed

    private void jRdbTransferenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbTransferenciaActionPerformed
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnV1000.setVisible(false);
        jBtnV5000.setVisible(false);
        jBtnV10000.setVisible(false);
        jBtnV20000.setVisible(false);
        jBtnV50000.setVisible(false);
        jBtnV100000.setVisible(false);
        jBtnVOtro.setVisible(false);
        jRdbPagoElectricidad.setVisible(false);
        jRdbPagoTelefono.setVisible(false);
        jRdbPagoServiciosMunicipales.setVisible(false);
        jRdbPagoElectricidad.setEnabled(false);
        jRdbPagoTelefono.setEnabled(false);
        jRdbPagoServiciosMunicipales.setEnabled(false);
    }//GEN-LAST:event_jRdbTransferenciaActionPerformed

    private void jRdbPagoServiciosPublicosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbPagoServiciosPublicosActionPerformed
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnV1000.setVisible(false);
        jBtnV5000.setVisible(false);
        jBtnV10000.setVisible(false);
        jBtnV20000.setVisible(false);
        jBtnV50000.setVisible(false);
        jBtnV100000.setVisible(false);
        jBtnVOtro.setVisible(false);
        jRdbPagoElectricidad.setVisible(true);
        jRdbPagoTelefono.setVisible(true);
        jRdbPagoServiciosMunicipales.setVisible(true);
        jRdbPagoElectricidad.setEnabled(true);
        jRdbPagoTelefono.setEnabled(true);
        jRdbPagoServiciosMunicipales.setEnabled(true);
    }//GEN-LAST:event_jRdbPagoServiciosPublicosActionPerformed

    private void jRdbPagoSinpeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbPagoSinpeActionPerformed
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnV1000.setVisible(false);
        jBtnV5000.setVisible(false);
        jBtnV10000.setVisible(false);
        jBtnV20000.setVisible(false);
        jBtnV50000.setVisible(false);
        jBtnV100000.setVisible(false);
        jBtnVOtro.setVisible(false);
        jRdbPagoElectricidad.setVisible(false);
        jRdbPagoTelefono.setVisible(false);
        jRdbPagoServiciosMunicipales.setVisible(false);
        jRdbPagoElectricidad.setEnabled(false);
        jRdbPagoTelefono.setEnabled(false);
        jRdbPagoServiciosMunicipales.setEnabled(false);
    }//GEN-LAST:event_jRdbPagoSinpeActionPerformed

    private void jRdbReporteMovimientosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbReporteMovimientosActionPerformed
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnV1000.setVisible(false);
        jBtnV5000.setVisible(false);
        jBtnV10000.setVisible(false);
        jBtnV20000.setVisible(false);
        jBtnV50000.setVisible(false);
        jBtnV100000.setVisible(false);
        jBtnVOtro.setVisible(false);
        jRdbPagoElectricidad.setVisible(false);
        jRdbPagoTelefono.setVisible(false);
        jRdbPagoServiciosMunicipales.setVisible(false);
        jRdbPagoElectricidad.setEnabled(false);
        jRdbPagoTelefono.setEnabled(false);
        jRdbPagoServiciosMunicipales.setEnabled(false);
    }//GEN-LAST:event_jRdbReporteMovimientosActionPerformed

    private void jRdbCambioPINActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRdbCambioPINActionPerformed
        jTxtOtroMonto.setVisible(false);
        jLblPressEnter.setVisible(false);
        jBtnV1000.setVisible(false);
        jBtnV5000.setVisible(false);
        jBtnV10000.setVisible(false);
        jBtnV20000.setVisible(false);
        jBtnV50000.setVisible(false);
        jBtnV100000.setVisible(false);
        jBtnVOtro.setVisible(false);
        jRdbPagoElectricidad.setVisible(false);
        jRdbPagoTelefono.setVisible(false);
        jRdbPagoServiciosMunicipales.setVisible(false);
        jRdbPagoElectricidad.setEnabled(false);
        jRdbPagoTelefono.setEnabled(false);
        jRdbPagoServiciosMunicipales.setEnabled(false);
    }//GEN-LAST:event_jRdbCambioPINActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmUsuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmUsuario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JButton jBtnSalir;
    private javax.swing.JButton jBtnSiguiente;
    private javax.swing.JButton jBtnV1000;
    private javax.swing.JButton jBtnV10000;
    private javax.swing.JButton jBtnV100000;
    private javax.swing.JButton jBtnV20000;
    private javax.swing.JButton jBtnV5000;
    private javax.swing.JButton jBtnV50000;
    private javax.swing.JButton jBtnVOtro;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLblPressEnter;
    private javax.swing.JRadioButton jRdbCambioPIN;
    private javax.swing.JRadioButton jRdbConsultaSaldo;
    private javax.swing.JRadioButton jRdbDeposito;
    private javax.swing.JRadioButton jRdbPagoElectricidad;
    private javax.swing.JRadioButton jRdbPagoServiciosMunicipales;
    private javax.swing.JRadioButton jRdbPagoServiciosPublicos;
    private javax.swing.JRadioButton jRdbPagoSinpe;
    private javax.swing.JRadioButton jRdbPagoTelefono;
    private javax.swing.JRadioButton jRdbReporteMovimientos;
    private javax.swing.JRadioButton jRdbRetiro;
    private javax.swing.JRadioButton jRdbTransferencia;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTxaVoucher;
    private javax.swing.JTextField jTxtOtroMonto;
    // End of variables declaration//GEN-END:variables
}
